# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hubris}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Wotton", "Josh Price", "James Britt"]
  s.date = %q{2010-08-25}
  s.description = %q{a bridge between Haskell and Ruby}
  s.email = %q{mwotton@gmail.com}
  s.executables = ["ghc_builder", "jhc_builder"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CommonErrors.txt",
     "HISTORY.markdown",
     "Manifest.txt",
     "PostInstall.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin-scripts/ghc_builder",
     "bin-scripts/jhc_builder",
     "bin/ghc_builder",
     "bin/jhc_builder",
     "examples/simple_inline/clean_and_run.sh",
     "examples/simple_inline/haskell_math.rb",
     "examples/simple_rack_app/Test.hs",
     "examples/simple_rack_app/config.ru",
     "examples/simple_rack_app/hsload.rb",
     "ext/stub/extconf.rb",
     "ext/stub/stub.c",
     "hubris.gemspec",
     "lib/Makefile",
     "lib/hubris.rb",
     "lib/stub.bundle",
     "lib/stub.so",
     "rspec.rake",
     "sample/Fibonacci.hs",
     "sample/config.ru",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/hubris_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mwotton/hubris}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{a bridge between Haskell and Ruby}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/hubris_spec.rb",
     "examples/simple_inline/haskell_math.rb",
     "examples/simple_rack_app/hsload.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

